[package]
name = "llmrl"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_envs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.1"
rayon = "1.11.0"
